### ISSUE TITLE
Error in admin webpage

### ISSUE THREAD

**Issue by javipalanca** [DinoThor/PyJabber#13]
When accessing localhost:9090 an error is thrown.
It seems that the templates are not where it should be. Maybe you need to modify the MANIFEST file and to reference the templates to the library path.

Error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jpalanca/pyjabber/webpage/build/index.html'
Unhandled exception
```

**Comment by DinoThor** [comment]
Fixed. Bad path reference in static file handler in aiohttp a68d72e
