### ISSUE TITLE
Testing issues on Roster

### ISSUE THREAD

**Issue by sosanzma** [DinoThor/PyJabber#18]
#### Problem
The `Roster` class directly depends on the `connection()` function to access the database, making it difficult to create unit tests. This causes issues such as:

1. **Inflexibility in Testing:** Cannot inject an in-memory or mocked database.
2. **Mocking Difficulty:** Using `with closing(connection()) as con:` interferes with proper connection mocking.

#### Proposed Solution
Refactor `Roster` to accept a database connection factory as an argument in its constructor. This will allow injecting different connections during testing.

### Proposed Refactoring
```python
class Roster:
    def __init__(self, db_connection_factory):
        self._db_connection_factory = db_connection_factory

    def retriveRoster(self, jid: str):
        with closing(self._db_connection_factory()) as con:
            res = con.execute("SELECT * FROM roster WHERE jid = ?", (jid,))
            roster = res.fetchall()
        return roster

    # Other methods...
``` 

where  

```python 
from pyjabber.db.database import connection

db_connection_factory = connection()
```

**Comment by DinoThor** [comment]
Fix done by @sosanzma
