### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by javipalanca** [DinoThor/PyJabber#4]
There is no `setup.py` file for installing the package.

A python project must have a `setup.py` file where the installation of the package is defined.
Currently, without the setup.py, the installation from pip fails.

There are also some issues in `requirements.txt`:
* pyjabber must not be included as a dependency of pyjabber itself!
* aiohttp dependency is missing
* There are several weird dependencies that should be confirmed if they are necessary or not (keyboard, PyAutoGUI, MouseInfo, PyGetWindow, PyMsgBox, pyperclip, PyRect, PyScreeze, pytweening, typer...)

**Comment by DinoThor** [comment]
Fixed
Change from pyproject.toml in favor of setup.py
